{
 "title": "LLM Inference Latency",
 "tags": [
  "inference",
  "latency"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Usage costs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(model) (llm_cost_total)", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Tokens used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  },
  {
   "title": "Input tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llm_input_tokens", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Output tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llm_output_tokens", "legendFormat": "{{model}}" }
   ]
  },
  {
   "title": "Total tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llm_total_tokens", "legendFormat": "{{model}}" }
   ]
  },
  { "title": "Inference", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "LLM Inference Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(llm_inference_duration_seconds_bucket[1m]))",
     "legendFormat": "{{model}} (chat)"
    }
   ]
  },
  {
   "title": "LLM Stream Inference Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(llm_stream_duration_seconds_bucket[1m]))",
     "legendFormat": "{{model}} (stream)"
    }
   ]
  },
  {
   "title": "LLM Inference Duration (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "rate(llm_inference_duration_seconds_sum[1m]) / rate(llm_inference_duration_seconds_count[1m])",
     "legendFormat": "{{model}} (avg)"
    }
   ]
  },
  {
   "title": "LLM Inference Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "rate(llm_inference_duration_seconds_count[1m])",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}