name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          # token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: python
          package-name: my-plants-ai